lang: ja
name: "山下慶倫"
title: "職務経歴書"
description: "データエンジニア・データアナリスト 山下慶倫の職務経歴書"
theme: jekyll-theme-cayman
url: "https://yoshinori77.github.io"
baseurl: "/career"
header_image: "/career/assets/images/header-bg.jpg"
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
